version: '3.3'

services:
  minio:
    image: bitnami/minio:latest
    restart: on-failure
    environment:
      - MINIO_ROOT_USER=store-app
      - MINIO_ROOT_PASSWORD=store-app
      - MINIO_DEFAULT_BUCKETS=store-app
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data: