"""Add Favorites Models

Revision ID: fc5dc36adf48
Revises: 2ba0d7edc982
Create Date: 2024-12-01 18:03:39.554760

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str | None = "fc5dc36adf48"
down_revision: str | None = "2ba0d7edc982"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorites",
        sa.Column("cart_outlet_guid", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("cart_outlet_guid", name=op.f("favorites_pkey")),
    )
    op.create_table(
        "favorites_goods",
        sa.Column("cart_outlet_guid", sa.String(length=255), nullable=False),
        sa.Column("good_guid", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_outlet_guid"], ["favorites.cart_outlet_guid"], name=op.f("favorites_goods_cart_outlet_guid_fkey")
        ),
        sa.ForeignKeyConstraint(["good_guid"], ["goods.guid"], name=op.f("favorites_goods_good_guid_fkey")),
        sa.PrimaryKeyConstraint("cart_outlet_guid", "good_guid", name=op.f("favorites_goods_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("favorites_goods")
    op.drop_table("favorites")
    # ### end Alembic commands ###
