"""CartGood Model

Revision ID: 2ba0d7edc982
Revises: 43ce38fec735
Create Date: 2024-11-19 22:38:18.493193

"""

from alembic import op
import sqlalchemy as sa

import db

# revision identifiers, used by Alembic.
revision: str | None = "2ba0d7edc982"
down_revision: str | None = "43ce38fec735"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cart_goods",
        sa.Column("cart_outlet_guid", sa.String(length=255), nullable=False),
        sa.Column("price_type_guid", db.models.mixins.GUID(), nullable=False),
        sa.Column("good_guid", sa.String(length=255), nullable=False),
        sa.Column("specification_guid", db.models.mixins.GUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_outlet_guid"], ["carts.cart_outlet_guid"], name=op.f("cart_goods_cart_outlet_guid_fkey")
        ),
        sa.ForeignKeyConstraint(["good_guid"], ["goods.guid"], name=op.f("cart_goods_good_guid_fkey")),
        sa.ForeignKeyConstraint(
            ["price_type_guid"], ["price_types.guid"], name=op.f("cart_goods_price_type_guid_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["specification_guid"], ["specifications.guid"], name=op.f("cart_goods_specification_guid_fkey")
        ),
        sa.PrimaryKeyConstraint("cart_outlet_guid", "good_guid", "specification_guid", name=op.f("cart_goods_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cart_goods")
    # ### end Alembic commands ###
