"""Add Order models

Revision ID: 3c7d3671172e
Revises: 3e776fcbe9dc
Create Date: 2024-12-09 11:25:02.587800

"""

from alembic import op
import sqlalchemy as sa

import db

# revision identifiers, used by Alembic.
revision: str | None = "3c7d3671172e"
down_revision: str | None = "3e776fcbe9dc"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("guid", db.models.mixins.GUID(), nullable=False),
        sa.Column("cart_outlet_guid", sa.String(length=255), nullable=False),
        sa.Column("status", sa.Enum("OPEN", "IN_PROCESS", "DONE", name="orderstatusenum"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("orders_pkey")),
        sa.UniqueConstraint("guid", name=op.f("orders_guid_key")),
    )
    op.create_index(op.f("orders_id_idx"), "orders", ["id"], unique=False)
    op.create_table(
        "order_goods",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("good_guid", sa.String(length=255), nullable=False),
        sa.Column("specification_guid", db.models.mixins.GUID(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["good_guid"], ["goods.guid"], name=op.f("order_goods_good_guid_fkey")),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("order_goods_order_id_fkey")),
        sa.ForeignKeyConstraint(
            ["specification_guid"], ["specifications.guid"], name=op.f("order_goods_specification_guid_fkey")
        ),
        sa.PrimaryKeyConstraint("order_id", "good_guid", "specification_guid", name=op.f("order_goods_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_goods")
    op.drop_index(op.f("orders_id_idx"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
